# Generated by Django 2.2 on 2019-04-15 23:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='member_since',
        ),
    ]
