# Generated by Django 2.2.1 on 2019-05-19 15:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0002_auto_20190519_1432'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notebook',
            old_name='author',
            new_name='user',
        ),
    ]
